server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  http:
    client:
      user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
      default-headers:
        Referer: http://www.google.com
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: http://radiomv.ru
#      name: radiomv
#    - url: https://www.lutherancathedral.ru
#      name: lutherancathedral
#    - url: https://ipfran.ru
#      name: ipfran.ru
    - url: https://dombulgakova.ru
      name: dombulgakova
    - url: https://www.nikoartgallery.com
      name: nikoartgallery.com
#    - url: https://volochek.life
#      name: volochek
    - url: https://dimonvideo.ru
      name: dimonvideo
    - url: https://et-cetera.ru
      name: ceteram


